version: '2.2'
services:
  cubestore:
    image: cubejs/cubestore:arm64-experimental-v2021-07-29
    environment:
      - CUBESTORE_REMOTE_DIR=/cube/data
    volumes:
      - .cubestore:/cube/data

  cube:
    image: cubejs/cube:latest
    ports:
      - 4000:4000
    environment:
      - CUBEJS_CUBESTORE_HOST=cubestore
      - CUBEJS_DB_HOST=demo-db.cube.dev
      - CUBEJS_DB_PORT=5432
      - CUBEJS_DB_NAME=ecom
      - CUBEJS_DB_USER=cube
      - CUBEJS_DB_PASS=12345
      - CUBEJS_DB_TYPE=postgres
      - CUBEJS_API_SECRET=da25704974549c4fb4e294f38cc3a764
      - CUBEJS_SCHEDULED_REFRESH_DEFAULT=true
      - CUBEJS_DEV_MODE=true
    depends_on:
      - cubestore
    links:
      - cubestore
    volumes:
      - ./schema:/cube/conf/schema